// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://qtluugcqnbgqdayvmnfjrpxudq.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lgr54y2su5ggxfsj6r6lewr7a4",
    "aws_content_delivery_bucket": "ra-data-appsync-20200225151343-hostingbucket-develop",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "http://ra-data-appsync-20200225151343-hostingbucket-develop.s3-website-ap-southeast-2.amazonaws.com"
};


export default awsmobile;
